name = "cloudlfare_worker"
main = "worker.ts"
compatibility_date = "2023-06-08"
workers_dev = true

[vars]
HASURA_GRAPHQL_ENGINE_ENDPOINT = "http://graphql-engine:8080"
HASURA_ADMIN_API_KEY = "myadminsecretkey"
LLM_INFERENCE_ENDPOINT=""
INFERENCE_API_KEY=""
PROJECT_ID = ""
